name: Build Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kloniraj repo
        uses: actions/checkout@v4

      - name: Instaliraj Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0

      - name: Instaliraj dependencies
        run: npm install

      - name: Pokreni build
        run: npm run build
